# Generated by Django 4.1.5 on 2023-01-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_games_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='История ходов',
            field=models.BinaryField(null=True),
        ),
    ]
