# Generated by Django 4.1.5 on 2023-02-05 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0003_game_история ходов'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='Игровые данные',
        ),
        migrations.RemoveField(
            model_name='game',
            name='История ходов',
        ),
        migrations.AddField(
            model_name='game',
            name='game_data',
            field=models.BinaryField(default=b'2345643211111111000000000000000000000000000000007777777789ABCA98', null=True, verbose_name='Игровые данные'),
        ),
        migrations.AddField(
            model_name='game',
            name='history',
            field=models.BinaryField(null=True, verbose_name='История ходов'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to=settings.AUTH_USER_MODEL, verbose_name='player1'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to=settings.AUTH_USER_MODEL, verbose_name='player2'),
        ),
    ]
