# Generated by Django 4.1.5 on 2023-02-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_game_игровые данные_remove_game_история ходов_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turn_of',
            field=models.BooleanField(default=True, verbose_name='Сейчас ходят'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_data',
            field=models.BinaryField(default=b'89ABCA9877777777000000000000000000000000000000001111111123456432', verbose_name='Игровые данные'),
        ),
    ]
