# Generated by Django 4.1.5 on 2023-02-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_turn_of_alter_game_game_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='turn_of',
        ),
        migrations.AddField(
            model_name='game',
            name='turn_of_white',
            field=models.BooleanField(default=True, verbose_name='Сейчас ходят белые'),
        ),
    ]
